favorites = [ "Qwen/Qwen3-VL-235B-A22B-Instruct", "Qwen/Qwen3-Next-80B-A3B-Instruct", "Qwen/Qwen3-235B-A22B-Instruct-2507",]
custom_models = [ "ZhipuAI/AutoGLM-Phone-9B",]
active_account = "默认"

[window]
x = -378
y = -1013
width = 668
height = 700
