active_account = "xxy"
favorites = [ "Qwen/Qwen3-235B-A22B-Instruct-2507", "Qwen/Qwen3-VL-235B-A22B-Instruct", "Qwen/Qwen3-Next-80B-A3B-Instruct",]
invisible = [ "deepseek-ai/DeepSeek-R1-Distill-Llama-8B", "deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B", "deepseek-ai/DeepSeek-R1-Distill-Qwen-14B", "deepseek-ai/DeepSeek-R1-Distill-Qwen-7B", "LLM-Research/c4ai-command-r-plus-08-2024", "LLM-Research/Llama-4-Maverick-17B-128E-Instruct", "Menlo/Jan-nano", "MiniMax/MiniMax-M1-80k", "mistralai/Ministral-8B-Instruct-2410", "mistralai/Mistral-Large-Instruct-2407", "mistralai/Mistral-Small-Instruct-2409", "opencompass/CompassJudger-1-32B-Instruct", "PaddlePaddle/ERNIE-4.5-0.3B-PT", "PaddlePaddle/ERNIE-4.5-21B-A3B-PT", "PaddlePaddle/ERNIE-4.5-300B-A47B-PT", "PaddlePaddle/ERNIE-4.5-VL-28B-A3B-PT", "Qwen/QVQ-72B-Preview", "Qwen/Qwen2.5-14B-Instruct", "Qwen/Qwen2.5-14B-Instruct-1M", "Qwen/Qwen2.5-32B-Instruct", "Qwen/Qwen2.5-72B-Instruct", "Qwen/Qwen2.5-7B-Instruct", "Qwen/Qwen2.5-7B-Instruct-1M", "Qwen/Qwen2.5-Coder-14B-Instruct", "Qwen/Qwen2.5-Coder-32B-Instruct", "Qwen/Qwen2.5-Coder-7B-Instruct", "Qwen/Qwen2.5-VL-32B-Instruct", "Qwen/Qwen2.5-VL-3B-Instruct", "Qwen/Qwen2.5-VL-72B-Instruct", "Qwen/Qwen2.5-VL-7B-Instruct", "Qwen/Qwen3-0.6B", "Qwen/Qwen3-1.7B", "Qwen/Qwen3-14B", "Qwen/Qwen3-235B-A22B", "Qwen/Qwen3-30B-A3B", "Qwen/Qwen3-8B", "Qwen/Qwen3-Coder-30B-A3B-Instruct", "XiaomiMiMo/MiMo-V2-Flash", "XGenerationLab/XiYanSQL-QwenCoder-32B-2504", "XGenerationLab/XiYanSQL-QwenCoder-32B-2412", "Shanghai_AI_Laboratory/Intern-S1-mini", "Shanghai_AI_Laboratory/Intern-S1", "Qwen/QwQ-32B-Preview", "Qwen/QwQ-32B", "stepfun-ai/step3", "Qwen/Qwen3-VL-8B-Thinking", "Qwen/Qwen3-VL-8B-Instruct", "Qwen/Qwen3-4B", "deepseek-ai/DeepSeek-R1-0528",]

[window]
x = 760
y = 176
width = 727
height = 600

[quotas.xxy]
user_remaining = "1999"
user_limit = "2000"

[quotas.ytc]
user_remaining = "1980"
user_limit = "2000"
